### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AriesQa** [PratikGarai/MNIST-Federated#2]
Hi, 
can you please help me, how to solve this error. 

03_Non IID Demo\server.py", line 24, in <module>
server_address = 'localhost:'+str(sys.argv[1]) , IndexError: list index out of range

Thanks

**Comment by PratikGarai** [comment]
Sorry for the late reply. 

You need to pass the port number to launch the server on as command line argument. 
Somewhat like
`python server.py 5000`

If you do not pass in the port number, sys.argv[1] is non existent and you get this error

**Comment by AriesQa** [comment]
ok. Thanks a lot for your response.
